name: audio_waveforms
description: A Flutter package that allow you to generate waveform while
  recording audio or from audio file.
version: 1.0.4
homepage: https://github.com/SimformSolutionsPvtLtd/audio_waveforms
issue_tracker: https://github.com/SimformSolutionsPvtLtd/audio_waveforms/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.simform.audio_waveforms
        pluginClass: AudioWaveformsPlugin
      ios:
        pluginClass: AudioWaveformsPlugin
